
project_id = "yosol-wallet"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = false
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:3000/**", "https://localhost:3000/**"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[realtime]
enabled = true

[functions]
enabled = true

[[functions.http]]
pattern = "voice-to-text"
function = "voice-to-text"

[[functions.http]]
pattern = "text-to-voice"
function = "text-to-voice"

[[functions.http]]
pattern = "assembly-transcribe"
function = "assembly-transcribe"

[[functions.http]]
pattern = "assembly-transcript-status"
function = "assembly-transcript-status"
