// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zodmcmnkgizuruxgeihn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZG1jbW5rZ2l6dXJ1eGdlaWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDAyNDgsImV4cCI6MjA1ODQxNjI0OH0.iCFvFsm4O66g-4bfHs-dS3boKIZ1-1nn4b0HeiRTjZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);